cloud:
  aws:
    credentials:
      access-key: AKIA6GOVQ4OO2Y5CMRFB
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: todo1storage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB